# Generated by Django 3.1.4 on 2021-01-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210113_0139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_Link',
            new_name='MovieLink',
        ),
    ]
